[package]
name = "lib-unix-socket-gpt"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.25.0", features = ["full"] }
unix_socket = { path="../unix_socket" }
anyhow = "1.0.69"
